#!/bin/bash

set -e

echo ""
echo "|"
echo "| Please run:"
echo "|"
echo "|  $ openstack-install"
echo "|"
echo "| As an unprivileged user to finish installation."
echo "|"
echo ""

#DEBHELPER#

exit 0
